version: '3.8'

services:
  keeper:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///keeper.db
      - SECRET_KEY=dev-secret-key
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - VAULT_URL=http://localhost:8200
      - VAULT_TOKEN=
    volumes:
      - ./:/app
    restart: unless-stopped